apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-api-dev

resources:
  - ../../base

images:
  - name: registry.example.com/sample-api
    newTag: dev-latest

replicas:
  - name: sample-api
    count: 1

patches:
  - target:
      kind: Deployment
      name: sample-api
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: LOG_LEVEL
          value: debug
