apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-api-production

resources:
  - ../../base

images:
  - name: registry.example.com/sample-api
    newTag: v1.4.2

replicas:
  - name: sample-api
    count: 5

patches:
  - target:
      kind: Deployment
      name: sample-api
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: LOG_LEVEL
          value: warn
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi
